### ISSUE TITLE
Failed with exception [WebDriverException] when using docker

### ISSUE THREAD

**Issue by yandong01** [vmware/crest#8]
### Describe the bug

Follow the guide using Docker, I got the error "Failed with exception [WebDriverException]" when post to crest.

### Reproduction steps

1. The post info:
post: http://xxxx:3000/crest/api/perceivable/cc-transcript
{
    "url": "https://www.google.com",
    "reporttype": 3
    
}

2. The docker logs:
see the screenshot.
![docker_log_screenshot](https://user-images.githubusercontent.com/29721589/192912465-9b8f09cf-3248-4a5b-bb55-b5771f6f8768.png)

3. The response:
{
    "status": {
        "error": "Failed with exception [WebDriverException]",
        "success": "False"
    }
}

### Expected behavior

The response should return 200

**Comment by cavedon** [comment]
This should be now resolved in #9

**Comment by yandong01** [comment]
The error "Failed with exception [WebDriverException]" is still reproduced with latest codes when post the request to the main API "/crest/api/all".

**Comment by yandong01** [comment]
@cavedon Please help to look at this issue.

> The error "Failed with exception [WebDriverException]" is still reproduced with latest codes when post the request to the main API "/crest/api/all".
